// export const ORM_IPADDR = "LOCALHOST" (FOR SIMULATOR) OR "IP ADDRESS OF DJANGO SERVER / LOCAL DEVICE" (FOR REAL IOS DEVICE);
export const ORM_IPADDR = "localhost"
// export const ORM_IPADDR = "LOCALHOST" (FOR SIMULATOR) OR "IP ADDRESS OF SOCKET SERVER / LOCAL DEVICE" (FOR REAL IOS DEVICE);
export const SOCKET_IPADDR = "localhost"