import { images } from "../constants";
export const articles = [
    [ {
        id: 1,
        name: "Medical Daily",
        media: images.coffee,
        headline: "Is Coffee Good For You? 8 Surprising Health Benefits Of Caffeine",
        info: "",
        footnote: "Mon, 19 Jul 2021",
        sc: 23,
        tag: 'article',
        HeaderCard: true,
        header: 'Lifestyle',
        category: 'lifestyle',
    },
    {
        id: 2,
        name: "Medical Daily",
        media: images.wine,
        headline: "Is Wine Good For You? 11 Surprising Healthy Benefits Of Vino",
        info: "More than just a celebratory drink or something to cap off a long day, wine can also give a lot of great health benefits so you have more reasons to enjoy your vino. Here's a list of wines health benefits along with the best wine brands you can get online.",
        footnote: "Fri, 23 Jul 2021",
        sc: 23,
        tag: 'article',
        HeaderCard: false,
        header: null,
        category: 'lifestyle',
    },
    {
        id: 3,
        name: "Medical Daily",
        media: images.earbuds,
        headline: "Are Wireless Earbuds Bad For Your Brain And Hearing?",
        info: "While wireless earbuds make taking calls, watching videos and listening to music on the go more convenient, can these earbuds be bad for your hearing? Here’s what you need to know.",
        footnote: "Tue, 20 Jul 2021",
        sc: 23,
        tag: 'article',
        HeaderCard: false,
        header: null,
        category: 'lifestyle',
    },
    {
        id: 4,
        name: "Medical Daily",
        media: images.outdoor,
        headline: "12 Best Healthy Outdoor Activities For Kids This Summer 2021",
        info: "It's summer 2021, are your kids already bored at home? Here are the best outdoor activities that you and your little ones can enjoy to stay healthy and active.",
        footnote: "Fri, 16 Jul 2021",
        sc: 23,
        tag: 'article',
        HeaderCard: false,
        header: null,
        category: 'lifestyle',
    } ],
    [ {
        id: 5,
        name: "Medical Daily",
        media: images.research,
        headline: "Novel therapeutic agent could be effective for treating cancers with certain gene mutations",
        info: "",
        footnote: "Fri, 23 Jul 2021",
        sc: 23,
        tag: 'article',
        HeaderCard: true,
        header: 'Research',
        category: 'research',
    },
    {
        id: 6,
        name: "Medical Daily",
        media: images.mhresearch,
        headline: "Study finds unacceptable mental health service shortfalls for children in high-income countries",
        info: "Most children with a mental health disorder are not receiving services to address their needs--according to a new study from researchers at Simon Fraser University's Children's Health Policy Centre.",
        footnote: "Fri, 23 Jul 2021",
        sc: 23,
        tag: 'article',
        HeaderCard: false,
        header: null,
        category: 'research',
    },
    {
        id: 7,
        name: "Medical Daily",
        media: images.gresearch,
        headline: "Gene therapy protects optic nerve cells and preserves vision in glaucoma mouse models",
        info: "A form of gene therapy protects optic nerve cells and preserves vision in mouse models of glaucoma, according to research supported by NIH's National Eye Institute.",
        footnote: "Fri, 23 Jul 2021",
        sc: 23,
        tag: 'article',
        HeaderCard: false,
        header: null,
        category: 'research',
    } ]
];