# Generated by Django 3.2.12 on 2022-06-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actions",
            old_name="col",
            new_name="action",
        ),
        migrations.RenameField(
            model_name="actions",
            old_name="col_value",
            new_name="authority",
        ),
    ]
