# Generated by Django 3.2.12 on 2022-06-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20220621_1703"),
    ]

    operations = [
        migrations.AddField(
            model_name="probations",
            name="pstatus",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="probations",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
    ]
