# Generated by Django 3.2.12 on 2022-06-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_auto_20220621_1726"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arbitrations",
            old_name="dateofaction",
            new_name="effective_date",
        ),
        migrations.RenameField(
            model_name="malpractices",
            old_name="classs",
            new_name="authority",
        ),
        migrations.RemoveField(
            model_name="arbitrations",
            name="status",
        ),
        migrations.RemoveField(
            model_name="malpractices",
            name="status",
        ),
        migrations.AddField(
            model_name="arbitrations",
            name="authority",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="arbitrations",
            name="docket",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="malpractices",
            name="docket",
            field=models.TextField(blank=True, null=True),
        ),
    ]
