# Generated by Django 3.2.12 on 2022-06-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_auto_20220621_2024"),
    ]

    operations = [
        migrations.RenameField(
            model_name="citations",
            old_name="effective_date",
            new_name="datecitationissued",
        ),
        migrations.RenameField(
            model_name="citations",
            old_name="end_date",
            new_name="dateresolved",
        ),
        migrations.AddField(
            model_name="citations",
            name="amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
