# Generated by Django 3.2.12 on 2022-07-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_otherstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_custom",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="middle name"
            ),
        ),
    ]
