# Generated by Django 3.2.12 on 2022-07-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_auto_20220716_1447"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_custom",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="user_custom",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="middle name"
            ),
        ),
    ]
