# Generated by Django 3.2.12 on 2022-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_auto_20220716_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="icon",
            field=models.ImageField(null=True, upload_to="static/img/"),
        ),
    ]
