# Generated by Django 3.2.12 on 2022-07-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_member_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visits",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                (
                    "approved_activity",
                    models.CharField(
                        choices=[
                            ("N", "NO EXERTION"),
                            ("L", "LIGHT"),
                            ("M", "MODERATE"),
                            ("V", "VIGOROUS"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
                (
                    "prov",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vaccinations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("vaccination_date", models.DateTimeField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
                (
                    "prov",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RxInsurance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurer", models.TextField()),
                ("id_member", models.TextField()),
                ("group_no", models.TextField()),
                ("benefit_plan", models.TextField()),
                ("rxbin", models.TextField()),
                ("rxpcn", models.TextField()),
                ("rxgrp", models.TextField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RxDiscount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurer", models.TextField()),
                ("id_member", models.TextField()),
                ("rxbin", models.TextField()),
                ("rxpcn", models.TextField()),
                ("rxgrp", models.TextField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prescribed_date", models.DateTimeField()),
                ("ndc", models.IntegerField(default=0)),
                ("expiration_date", models.DateTimeField()),
                ("lot_no", models.TextField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedInsurance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurer", models.TextField()),
                ("id_member", models.TextField()),
                ("group_no", models.TextField()),
                ("benefit_plan", models.TextField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="mdNotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
                (
                    "prov",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="labs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab", models.FileField(upload_to="labs/%Y/%m/%d/")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
                (
                    "prov",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BodyComp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmi", models.IntegerField(default=0)),
                ("bf", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
                (
                    "measurement",
                    models.CharField(
                        choices=[("S", "Standard"), ("M", "Metric")], max_length=8
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
            ],
        ),
    ]
