# Generated by Django 3.2.12 on 2022-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0011_bodycomp_labs_mdnotes_medinsurance_prescription_rxdiscount_rxinsurance_vaccinations_visits",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="icon",
            field=models.ImageField(null=True, upload_to="img/"),
        ),
    ]
