# Generated by Django 3.2.12 on 2022-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_member_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vaccinations",
            old_name="name",
            new_name="vaccination",
        ),
        migrations.AddField(
            model_name="labs",
            name="status",
            field=models.CharField(
                choices=[("O", "ORDERED"), ("C", "COMPLETE")], default="O", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="labs",
            name="uploaded",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mdnotes",
            name="uploaded",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
