# Generated by Django 3.2.12 on 2022-07-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_auto_20220720_1425"),
    ]

    operations = [
        migrations.AddField(
            model_name="labs",
            name="brief_desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
