# Generated by Django 3.2.12 on 2022-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_labs_brief_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="medinsurance",
            name="card",
            field=models.FileField(
                blank=True, null=True, upload_to="medical_insurance/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="medinsurance",
            name="uploaded",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="rxdiscount",
            name="card",
            field=models.FileField(
                blank=True, null=True, upload_to="rx_discount/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="rxdiscount",
            name="uploaded",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="rxinsurance",
            name="card",
            field=models.FileField(
                blank=True, null=True, upload_to="rx_insurance/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="rxinsurance",
            name="uploaded",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
