# Generated by Django 3.2.12 on 2022-07-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_auto_20220720_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_custom",
            name="county_code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="user_custom",
            name="ssn",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="SSN"
            ),
        ),
        migrations.AlterField(
            model_name="user_custom",
            name="street_address2",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user_custom",
            name="street_address3",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
