# Generated by Django 3.2.12 on 2022-07-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_auto_20220721_2201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodycomp",
            name="bf",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="This is a regular number (integer) e.g. 25% BF -> 25",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bodycomp",
            name="bmi",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="This is a regular decimal number (float) e.g. 24.4 BMI -> 24.4",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bodycomp",
            name="height",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="inches for standard / centimeters for metric",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bodycomp",
            name="measurement",
            field=models.CharField(
                choices=[("S", "Standard"), ("M", "Metric")],
                help_text="standard / metric",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="bodycomp",
            name="weight",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="lbs for standard / kgs for metric",
                max_digits=8,
            ),
        ),
    ]
