# Generated by Django 3.2.12 on 2022-08-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_auto_20220721_2304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodycomp",
            name="bf",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="This is a regular decimal number (float) e.g. 25.3% BF -> 25.3",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="m_status",
            field=models.CharField(
                choices=[
                    ("I", "IN LINE"),
                    ("W", "WAITING"),
                    ("B", "BEING SEEN"),
                    ("A", "ARRIVED"),
                    ("N", "NO-SHOW"),
                    ("L", "LEFT"),
                    ("S", "SEEN"),
                    ("ON", "ON-BOARDING"),
                    ("OFF", "OFF-BOARDING"),
                    ("Z", "Z"),
                ],
                default="ON",
                max_length=12,
            ),
        ),
    ]
