# Generated by Django 3.2.12 on 2022-08-05 03:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_auto_20220804_1606"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medinfo_release",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp_time", models.DurationField(default=datetime.timedelta(days=60))),
                ("date_released", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
                (
                    "prov",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.provider",
                    ),
                ),
            ],
        ),
    ]
