# Generated by Django 3.2.12 on 2022-08-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_medinfo_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="medinfo_release",
            name="released",
            field=models.BooleanField(default=False),
        ),
    ]
