# Generated by Django 3.2.12 on 2022-08-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_medinfo_release_released"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(default=None, max_length=256)),
                ("msg", models.TextField()),
                ("time", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("M", "Message"),
                            ("I", "Announcment"),
                            ("A", "Alert"),
                            ("R", "Request"),
                        ],
                        help_text="Type of notification",
                        max_length=11,
                    ),
                ),
                (
                    "fromm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FROM",
                        to="base.baseuser",
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TO",
                        to="base.baseuser",
                    ),
                ),
            ],
        ),
    ]
