# Generated by Django 3.2.12 on 2022-08-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conn_id", models.CharField(default=None, max_length=256)),
                ("time", models.DateTimeField(auto_now=True)),
                ("connected", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conn_user",
                        to="base.baseuser",
                    ),
                ),
            ],
        ),
    ]
