# Generated by Django 3.2.12 on 2022-08-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="conn_id",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
