# Generated by Django 3.2.12 on 2022-08-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_alter_connection_conn_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="fromm",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="to",
        ),
        migrations.AddField(
            model_name="notification",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="base.baseuser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="base.baseuser",
            ),
            preserve_default=False,
        ),
    ]
