# Generated by Django 3.2.12 on 2022-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_auto_20220808_0216"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="readd",
            field=models.BooleanField(default=False),
        ),
    ]
