# Generated by Django 3.2.12 on 2022-08-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_notification_readd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="readd",
        ),
    ]
