# Generated by Django 3.2.12 on 2022-08-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_remove_notification_readd"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="read_msg",
            field=models.BooleanField(default=False),
        ),
    ]
