# Generated by Django 3.2.12 on 2022-08-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_notification_read_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="mdnotes",
            name="assessment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mdnotes",
            name="chief_complaint",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mdnotes",
            name="exam",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mdnotes",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mdnotes",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
