# Generated by Django 3.2.12 on 2022-09-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0028_auto_20220814_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="prescriber",
            field=models.IntegerField(
                blank=True, help_text="National Provider Identifier", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bodycomp",
            name="measurement",
            field=models.CharField(
                choices=[("S", "Standard"), ("M", "Metric")],
                default="Standard",
                help_text="standard / metric",
                max_length=8,
            ),
        ),
    ]
