# Generated by Django 3.2.12 on 2022-09-17 02:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_auto_20220911_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="about",
            field=ckeditor.fields.RichTextField(default="hello"),
            preserve_default=False,
        ),
    ]
