# Generated by Django 3.2.12 on 2022-10-10 05:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_alter_provider_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patientvisit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateTimeField(auto_now=True)),
                ("counter", models.IntegerField(default=0)),
                ("dr_rating", models.IntegerField(blank=True, default=0, null=True)),
                ("staff_rating", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "bedside_rating",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "office_rating",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "asked",
                    models.CharField(
                        choices=[
                            ("Y", "ASKING"),
                            ("N", "NOT ASKED"),
                            ("A", "ANSWERED"),
                        ],
                        default="N",
                        max_length=11,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reportcard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "provider_specialty",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("question", models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "SATISFIED"),
                    ("2", "NOT SATISFIED"),
                    ("3", "ECSTATIC"),
                    ("4", "DISAPPOINTED"),
                    ("5", "OVER"),
                    ("6", "LIVID"),
                ],
                max_length=13,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="responded",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="response",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="submitted",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="comment",
            name="published",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ESC", "ESCROW"),
                    ("RTC", "REQUEST TO CANCEL"),
                    ("RD", "REQUEST DENIED"),
                    ("RA", "REQUEST APPROVED"),
                    ("STP", "SUMBITTED TO PUBLISH"),
                    ("P", "PUBLISHED"),
                ],
                max_length=65,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="about",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="tip",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Provider_reportcard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        choices=[("Y", "YES"), ("N", "NO")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("ask_date", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
                (
                    "prov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.provider"
                    ),
                ),
                (
                    "reportcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.reportcard",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.patientvisit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patientvisit",
            name="prov",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.provider"
            ),
        ),
    ]
