# Generated by Django 3.2.12 on 2022-10-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0033_auto_20221022_1935"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider_reportcard",
            name="answer_cnt",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="provider_reportcard",
            name="question_score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="correct_answer",
            field=models.CharField(
                blank=True, choices=[("Y", "YES"), ("N", "NO")], max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (6, "SATISFIED"),
                    (-6, "NOT SATISFIED"),
                    (8, "ECSTATIC"),
                    (-8, "DISAPPOINTED"),
                    (12, "OVER"),
                    (-12, "LIVID"),
                ],
                default=6,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProviderReportCards",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments_score", models.IntegerField(default=0)),
                ("questions_score", models.IntegerField(default=0)),
                ("staff_score", models.IntegerField(default=0)),
                ("office_score", models.IntegerField(default=0)),
                ("bedside_score", models.IntegerField(default=0)),
                ("dr_score", models.IntegerField(default=0)),
                ("report_date", models.DateTimeField()),
                (
                    "prov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.provider"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dr_rating", models.IntegerField(blank=True, default=0, null=True)),
                ("staff_rating", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "bedside_rating",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "office_rating",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("score", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "prov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.provider"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderQuestionsReportCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_avg", models.IntegerField(default=0)),
                (
                    "question_rating",
                    models.CharField(
                        blank=True,
                        choices=[("GOOD", "GOOD"), ("POOR", "POOR")],
                        max_length=4,
                        null=True,
                    ),
                ),
                ("report_date", models.DateTimeField()),
                (
                    "prov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.provider"
                    ),
                ),
                (
                    "reportcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.reportcard",
                    ),
                ),
            ],
        ),
    ]
