# Generated by Django 3.2.12 on 2022-11-20 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_auto_20221024_2300"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medinfo_release",
            name="prov",
        ),
        migrations.AddField(
            model_name="medinfo_release",
            name="assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.baseuser",
            ),
        ),
    ]
