# Generated by Django 3.2.12 on 2022-11-25 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0036_alter_medinfo_release_exp_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medinfo_release",
            name="exp_time",
            field=models.DurationField(default=datetime.timedelta(days=60)),
        ),
    ]
