# Generated by Django 3.2.12 on 2022-11-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0037_alter_medinfo_release_exp_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pcodes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=9)),
                ("desc", models.TextField()),
                ("load_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.user_custom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mcodes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2)),
                ("desc", models.TextField()),
                ("load_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.user_custom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dcodes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=9)),
                ("desc", models.TextField()),
                ("cat", models.CharField(max_length=9)),
                ("cat_desc", models.CharField(max_length=256)),
                ("load_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.user_custom",
                    ),
                ),
            ],
        ),
    ]
