# Generated by Django 3.2.12 on 2022-11-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0038_dcodes_mcodes_pcodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcodes",
            name="cat",
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pcodes",
            name="cat_desc",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
