# Generated by Django 3.2.12 on 2022-11-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0039_auto_20221125_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcodes",
            name="cat",
            field=models.CharField(max_length=128),
        ),
    ]
