# Generated by Django 3.2.12 on 2022-11-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0040_alter_pcodes_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcodes",
            name="cat",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pcodes",
            name="cat_desc",
            field=models.CharField(max_length=32),
        ),
    ]
