# Generated by Django 3.2.12 on 2022-11-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0041_auto_20221125_1622"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dcodes",
            old_name="cat",
            new_name="cat_code",
        ),
    ]
