# Generated by Django 3.2.12 on 2022-11-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0042_rename_cat_dcodes_cat_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dcodes",
            old_name="cat_desc",
            new_name="cat",
        ),
    ]
