# Generated by Django 3.2.12 on 2022-11-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0043_rename_cat_desc_dcodes_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="dcodes",
            name="cat_desc",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
