# Generated by Django 3.2.12 on 2022-12-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0044_dcodes_cat_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientvisit",
            name="billed",
            field=models.BooleanField(default=False),
        ),
    ]
