# Generated by Django 3.2.12 on 2022-12-13 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0045_patientvisit_billed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim_Detail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.IntegerField(default=0)),
                ("fromdate", models.DateTimeField()),
                ("todate", models.DateTimeField()),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="This is the amount charged for the procedure",
                        max_digits=15,
                    ),
                ),
                ("units", models.IntegerField(default=0)),
                (
                    "location",
                    models.TextField(blank=True, default="location", null=True),
                ),
                ("dx_pointer", models.CharField(default=":", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="POScodes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2)),
                ("desc", models.TextField()),
                ("cat_desc", models.TextField()),
                ("load_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.user_custom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Claim_Mx",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.claim_detail",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.mcodes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Claim_Info",
            fields=[
                (
                    "claimid",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                (
                    "total_amt",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="This is the total amount charged for the claim",
                        max_digits=15,
                    ),
                ),
                ("loaded", models.DateTimeField(auto_now=True)),
                ("submitted", models.BooleanField(default=False)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.provider"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.member"
                    ),
                ),
                (
                    "primary_diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.dcodes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Claim_Dx",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.IntegerField(default=0)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.claim_info",
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.dcodes"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="claim_detail",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.claim_info"
            ),
        ),
        migrations.AddField(
            model_name="claim_detail",
            name="place_of_service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.poscodes"
            ),
        ),
        migrations.AddField(
            model_name="claim_detail",
            name="procedure_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.pcodes"
            ),
        ),
        migrations.AddField(
            model_name="claim_detail",
            name="rendering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.provider"
            ),
        ),
    ]
