# Generated by Django 3.2.12 on 2022-12-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0046_auto_20221212_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim_detail",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Referrer",
                to="base.provider",
            ),
        ),
    ]
