# Generated by Django 3.2.12 on 2022-12-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0047_claim_detail_referrer"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="billing",
            field=models.BooleanField(default=True),
        ),
    ]
