# Generated by Django 3.2.12 on 2022-12-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0048_provider_billing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim_info",
            name="billing",
            field=models.ForeignKey(
                limit_choices_to={"billing": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="base.provider",
            ),
        ),
        migrations.CreateModel(
            name="RenderingProvider",
            fields=[
                (
                    "provider_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.provider",
                    ),
                ),
                (
                    "billing_prov",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_provider",
                        to="base.provider",
                    ),
                ),
            ],
            bases=("base.provider",),
        ),
    ]
