# Generated by Django 3.2.12 on 2022-12-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0049_auto_20221215_0923"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renderingprovider",
            name="provider_ptr",
        ),
        migrations.AddField(
            model_name="renderingprovider",
            name="rendering_provider",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="rendering_provider",
                serialize=False,
                to="base.provider",
            ),
            preserve_default=False,
        ),
    ]
