# Generated by Django 3.2.12 on 2022-12-18 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0051_alter_claim_info_claimid"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientvisit",
            name="claim",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.claim_info",
            ),
        ),
    ]
