# Generated by Django 3.2.12 on 2023-01-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0053_auto_20221229_0003"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerratings",
            name="update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
