# Generated by Django 3.2.12 on 2023-01-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0055_patientvisit_commentt"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerratings",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POOR", "POOR"),
                    ("FAIR", "FAIR"),
                    ("EXCELLENT", "EXCELLENT"),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="providerquestionsreportcard",
            name="question_rating",
            field=models.CharField(
                blank=True,
                choices=[("POOR", "POOR"), ("GOOD", "GOOD")],
                max_length=4,
                null=True,
            ),
        ),
    ]
