# Generated by Django 3.2.12 on 2023-01-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0056_auto_20230103_0639"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcodes",
            name="cat_desc",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="providerratings",
            name="score",
            field=models.IntegerField(default=662),
        ),
    ]
