# Generated by Django 3.2.12 on 2023-01-19 03:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0057_auto_20230111_1232"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_duration",
                    models.CharField(
                        choices=[
                            ("10", "10 Minute"),
                            ("15", "15 Minute"),
                            ("25", "25 Minute"),
                            ("30", "30 Minute"),
                            ("45", "45 Minute"),
                            ("60", "60 Minute"),
                        ],
                        max_length=2,
                    ),
                ),
                ("appointment_type_name", models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateTimeField()),
                (
                    "appointment_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.appointmenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfficeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_time", models.TimeField(default=datetime.time(6, 0))),
                ("close_time", models.TimeField(default=datetime.time(17, 0))),
                (
                    "prov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.provider"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="availability",
            name="prov",
        ),
        migrations.RemoveField(
            model_name="availability",
            name="slot",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("M", "Message"),
                    ("I", "Announcment"),
                    ("A", "Alert"),
                    ("R", "Request"),
                    ("X", "Answered"),
                    ("Z", "Request Answered"),
                    ("B", "Approved 30 days"),
                    ("C", "Approved 90 days"),
                    ("D", "Approved indefinitely"),
                    ("N", "Not approved"),
                ],
                help_text="Type of notification",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Availability",
        ),
        migrations.DeleteModel(
            name="TimeSlot",
        ),
        migrations.AddField(
            model_name="office",
            name="config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.officeconfig",
            ),
        ),
    ]
