# Generated by Django 3.2.12 on 2023-01-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0058_auto_20230118_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("D", "DONE"), ("C", "CANCELED"), ("P", "PENDING")],
                default="P",
                max_length=1,
                null=True,
            ),
        ),
    ]
