# Generated by Django 3.2.12 on 2023-04-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0059_office_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_custom",
            name="account_number",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="user_custom",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "privilege",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Admin"),
                            ("P", "Provider"),
                            ("1", "Scheduling Staff"),
                            ("2", "Record Notes Staff"),
                            ("3", "Assistant Staff"),
                            ("C", "Caretaker"),
                            ("R", "Case Manager"),
                            ("T", "Authority"),
                            ("G", "Gaurdian"),
                            ("N", "None"),
                        ],
                        default="T",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.baseuser",
                    ),
                ),
            ],
        ),
    ]
