# Generated by Django 3.2.12 on 2023-08-12 17:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0060_auto_20230423_1718"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="lobby_city",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="lobby_country",
            field=django_countries.fields.CountryField(
                default="US", max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="lobby_county_code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="lobby_phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="lobby_state",
            field=models.CharField(
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="lobby_street_address",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="lobby_zipcode",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="preferred_name",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="preferred name"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="provider_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="provider email address",
            ),
        ),
        migrations.AddField(
            model_name="renderingprovider",
            name="use_billing_lobby_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="queueconfig",
            name="status",
            field=models.CharField(
                choices=[("P", "PAUSED"), ("A", "ACTIVE")], max_length=6
            ),
        ),
    ]
