# Generated by Django 3.2.12 on 2025-05-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0062_alter_provider_salutation"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueconfig",
            name="seen_avg",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="queueconfig",
            name="waiting_to_be_seen_avg",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="StatusChangeLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("I", "IN LINE"),
                            ("W", "WAITING"),
                            ("B", "BEING SEEN"),
                            ("A", "ARRIVED"),
                            ("N", "NO-SHOW"),
                            ("L", "LEFT"),
                            ("S", "SEEN"),
                            ("ON", "ON-BOARDING"),
                            ("OFF", "OFF-BOARDING"),
                            ("Z", "Z"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("I", "IN LINE"),
                            ("W", "WAITING"),
                            ("B", "BEING SEEN"),
                            ("A", "ARRIVED"),
                            ("N", "NO-SHOW"),
                            ("L", "LEFT"),
                            ("S", "SEEN"),
                            ("ON", "ON-BOARDING"),
                            ("OFF", "OFF-BOARDING"),
                            ("Z", "Z"),
                        ],
                        max_length=3,
                    ),
                ),
                ("change_time", models.DateTimeField(auto_now_add=True)),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="base.queue",
                    ),
                ),
            ],
        ),
    ]
