import { COLORS } from '../constants';

export const notis1 = {
    notifications: [
        {
            latest: {
                id: '181',
                msg: "I'm requesting access to your medical records.",
                notification_type: 'R',
                read_msg: 'False',
                receiver: {
                    user: {
                        email: 'bradley34@example.org',
                        first_name: 'Bradley',
                        icon: null,
                        id: '1760',
                        last_name: 'Nolen',
                        middle_name: 'Davis',
                        username: 'bradley34@example.org',
                    },
                },
                sender: {
                    user: {
                        email: 'Benatti.atwood.david.wade@provider.com',
                        first_name: 'David',
                        icon: null,
                        id: '1542',
                        last_name: 'Wade',
                        middle_name: 'Benatti atwood',
                        username: 'Benatti.atwood.david.wade@provider.com',
                    },
                },
                thread_id: '3302',
                time: '2024-03-25T16:25:24.978317-05:00',
            },
            notifications: [
                {
                    id: '175',
                    msg: "I'm requesting access to your medical records.",
                    notification_type: 'X',
                    read_msg: 'False',
                    receiver: {
                        user: {
                            email: 'bradley34@example.org',
                            first_name: 'Bradley',
                            icon: null,
                            id: '1760',
                            last_name: 'Nolen',
                            middle_name: 'Davis',
                            username: 'bradley34@example.org',
                        },
                    },
                    sender: {
                        user: {
                            email: 'Benatti.atwood.david.wade@provider.com',
                            first_name: 'David',
                            icon: null,
                            id: '1542',
                            last_name: 'Wade',
                            middle_name: 'Benatti atwood',
                            username: 'Benatti.atwood.david.wade@provider.com',
                        },
                    },
                    thread_id: '3302',
                    time: '2023-03-27T17:34:34.107897-05:00',
                },
                {
                    id: '177',
                    msg: 'Approved',
                    notification_type: 'D',
                    read_msg: 'False',
                    receiver: { user: [ Object ] },
                    sender: { user: [ Object ] },
                    thread_id: '3302',
                    time: '2023-03-27T17:34:34.114906-05:00',
                },
                {
                    id: '77',
                    msg: 'Test',
                    notification_type: 'M',
                    read_msg: 'False',
                    receiver: { user: [ Object ] },
                    sender: { user: [ Object ] },
                    thread_id: '3302',
                    time: '2022-10-18T07:40:35.852497-05:00',
                },
                {
                    id: '180',
                    msg: 'Testing',
                    notification_type: 'M',
                    read_msg: 'False',
                    receiver: { user: [ Object ] },
                    sender: { user: [ Object ] },
                    thread_id: '3302',
                    time: '2023-08-25T22:51:26.133780-05:00',
                },
                {
                    id: '181',
                    msg: "I'm requesting access to your medical records.",
                    notification_type: 'R',
                    read_msg: 'False',
                    receiver: { user: [ Object ] },
                    sender: { user: [ Object ] },
                    thread_id: '3302',
                    time: '2024-03-25T16:25:24.978317-05:00',
                },
                {
                    id: '182',
                    msg: 'Please select',
                    notification_type: 'R',
                    read_msg: 'False',
                    receiver: { user: [ Object ] },
                    sender: { user: [ Object ] },
                    thread_id: '3302',
                    time: '2024-03-25T16:25:24.978317-05:00',
                },
            ],
            thread_id: '3302',
        },
    ],
};
