import { user1, user2, user3, user4 } from "./users";

const provider1 = {
    Accusations: [],
    Actions: [],
    Arbitrations: [],
    Citations: [
        {
            amount: 350,
            cause: 'VIOLATION OF TERM OR CONDITION OF PROBATION.',
            datecitationissued: '06-Dec-2018',
            dateresolved: '2018-12-21 06:00:00+00:00',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            resolved: 'Y',
        },
    ],
    Convictions: [
        {
            classs: 'MISDEMEANOR',
            court: 'SUPERIOR COURT OF CALIFORNIA, COUNTY OF SAN DIEGO',
            effective_date: '30-Mar-2015',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            sentence: 'FIVE YEARS PROBATION WITH TERMS AND CONDITIONS.',
            summary:
                'PLED GUILTY TO TWO COUNTS OF VIOLATING PENAL CODE SECTION 273.5(A) (CORPORAL INJURY ON SPOUSE OR COHABITANT).',
        },
    ],
    License: [
        {
            licensenumber: '137214',
            licensetype: 'A',
            no_practice_permitted: '0',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            shortdescription: 'Current',
        },
    ],
    Malpractices: [],
    Number_negatives_v: [],
    Number_of_negatives: [
        { prov: '1542', prov_firstname: 'David', prov_lastname: 'Wade', sum: 3 },
    ],
    Probations: [
        {
            age_of_probation: '5 Years, 0 Months, and 0 Days',
            casenumber: '8002015018436',
            effective_date: '02-Nov-2017',
            end_date: '02-Nov-2022',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            pstatus: '11',
            status: 'incomplete',
            summary:
                "DR. BENATTI ATWOOD ADMITTED TO BEING CONVICTED OF A MISDEMEANOR COUNT OF CORPORAL INJURY ON A SPOUSE OR COHABITANT; USING DRUGS IN A MANNER AS TO BE DANGEROUS OR INJURIOUS TO HIMSELF, ANOTHER PERSON, OR TO THE PUBLIC; AND ENGAGING IN UNPROFESSIONAL CONDUCT.  EFFECTIVE 11/02/2017, REVOKED, STAYED, PLACED ON FIVE YEARS' PROBATION UNTIL ANTICIPATED END DATE OF 11/02/2022.  TERMS AND CONDITIONS INCLUDE, BUT ARE NOT LIMITED TO, ABSTAINING FROM THE USE OF CONTROLLED SUBSTANCES AND ALCOHOL, COMPLETING AN ETHICS COURSE AND AN ANGER MANAGEMENT COURSE, SUBMITTING TO A PSYCHIATRIC EVALUATION, ATTENDING PSYCHOTHERAPY, NOTIFICATION OF EMPLOYER, SUBMITTING TO BIOLOGICAL FLUID TESTING, ATTENDING SUBSTANCE ABUSE SUPPORT GROUP MEETINGS, OBTAINING A WORKSITE MONITOR, SUBMITTING PROOF OF NOTIFICATION OF DECISION AND ACCUSATION TO REQUIRED PARTIES, PROHIBITED FROM SUPERVISING PHYSICIAN ASSISTANTS AND ADVANCED PRACTICE NURSES, SUBMITTING QUARTERLY DECLARATIONS OF COMPLIANCE WITH ALL CONDITIONS OF PROBATION, COMPLYING WITH BOARD'S PROBATION UNIT, PROHIBITED FROM ENGAGING IN THE PRACTICE OF MEDICINE IN DR. BENATTI ATWOOD'S OR PATIENT'S PLACE OF RESIDENCE, UNLESS THE PATIENT RESIDES IN A SKILLED NURSING FACILITY OR OTHER SIMILAR LICENSED FACILITY, AND PAYING COSTS ASSOCIATED WITH PROBATION MONITORING.",
        },
        {
            age_of_probation: '5 Years, 0 Months, and 0 Days',
            casenumber: '8002015018436',
            effective_date: '02-Nov-2017',
            end_date: '02-Nov-2022',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            pstatus: '11',
            status: 'incomplete',
            summary:
                'FIVE YEARS PROBATION VARIOUS TERMS CONDITIONS PROBATION ATWOOD PROHIBITED SUPERVISING PHYSICIAN ASSISTANTS ADVANCED PRACTICE NURSES.',
        },
    ],
    Provider: {
        about: 'Dummy',
        badge: {
            badge: 'Bronze',
            badge_type: 'Bronze',
            icon: 'http://10.0.0.25/media/static/img/star_empty_J3iES2w.png',
            tier: '1',
        },
        icon: 'http://10.0.0.25/media/static/img/158927_6IGzGKC_YrQuS8o_HPZyBVY.jpg',
        npi: 1234567890,
        preferred_name: 'Wade',
        prov_taxonomy_code: 'Allergy',
        provider: { user: user1 },
        provider_id: 1542,
        salutation: null,
        specialty_code: 'ALLERGY',
        tip: 'Dummy',
        votee: 0,
    },
    QueueConfig: {
        capacity: 15,
        close_time: '18:00:00',
        end_before_close: 1,
        est_wait_time: 2,
        inqueue: -1,
        open_time: '06:00:00',
        pause_time: 1,
        prov: '1542',
        prov_firstname: 'David',
        prov_lastname: 'Wade',
        status: 'A',
        time_before_noshow: 1,
        time_between_patients: 0,
    },
    Ratings: [
        { rating: 216, type: 'doctor' },
        { rating: 73, type: 'staff' },
        { rating: 66, type: 'office' },
        { rating: 60, type: 'bedisde' },
    ],
};
const provider2 = {
    Accusations: [],
    Actions: [],
    Arbitrations: [],
    Citations: [
        {
            amount: 350,
            cause: 'VIOLATION OF TERM OR CONDITION OF PROBATION.',
            datecitationissued: '06-Dec-2018',
            dateresolved: '2018-12-21 06:00:00+00:00',
            prov: '1542',
            prov_firstname: 'Nyree',
            prov_lastname: 'Padilla',
            resolved: 'Y',
        },
    ],
    Convictions: [
        {
            classs: 'MISDEMEANOR',
            court: 'SUPERIOR COURT OF CALIFORNIA, COUNTY OF SAN DIEGO',
            effective_date: '30-Mar-2015',
            prov: '1542',
            prov_firstname: 'Nyree',
            prov_lastname: 'Padilla',
            sentence: 'FIVE YEARS PROBATION WITH TERMS AND CONDITIONS.',
            summary:
                'PLED GUILTY TO TWO COUNTS OF VIOLATING PENAL CODE SECTION 273.5(A) (CORPORAL INJURY ON SPOUSE OR COHABITANT).',
        },
    ],
    License: [
        {
            licensenumber: '137214',
            licensetype: 'A',
            no_practice_permitted: '0',
            prov: '1542',
            prov_firstname: 'Nyree',
            prov_lastname: 'Padilla',
            shortdescription: 'Current',
        },
    ],
    Malpractices: [],
    Number_negatives_v: [],
    Number_of_negatives: [
        { prov: '1542', prov_firstname: 'Nyree', prov_lastname: 'Padilla', sum: 3 },
    ],
    Probations: [
        {
            age_of_probation: '5 Years, 0 Months, and 0 Days',
            casenumber: '8002015018436',
            effective_date: '02-Nov-2017',
            end_date: '02-Nov-2022',
            prov: '1542',
            prov_firstname: 'Nyree',
            prov_lastname: 'Padilla',
            pstatus: '11',
            status: 'incomplete',
            summary:
                "DR. BENATTI ATWOOD ADMITTED TO BEING CONVICTED OF A MISDEMEANOR COUNT OF CORPORAL INJURY ON A SPOUSE OR COHABITANT; USING DRUGS IN A MANNER AS TO BE DANGEROUS OR INJURIOUS TO HIMSELF, ANOTHER PERSON, OR TO THE PUBLIC; AND ENGAGING IN UNPROFESSIONAL CONDUCT.  EFFECTIVE 11/02/2017, REVOKED, STAYED, PLACED ON FIVE YEARS' PROBATION UNTIL ANTICIPATED END DATE OF 11/02/2022.  TERMS AND CONDITIONS INCLUDE, BUT ARE NOT LIMITED TO, ABSTAINING FROM THE USE OF CONTROLLED SUBSTANCES AND ALCOHOL, COMPLETING AN ETHICS COURSE AND AN ANGER MANAGEMENT COURSE, SUBMITTING TO A PSYCHIATRIC EVALUATION, ATTENDING PSYCHOTHERAPY, NOTIFICATION OF EMPLOYER, SUBMITTING TO BIOLOGICAL FLUID TESTING, ATTENDING SUBSTANCE ABUSE SUPPORT GROUP MEETINGS, OBTAINING A WORKSITE MONITOR, SUBMITTING PROOF OF NOTIFICATION OF DECISION AND ACCUSATION TO REQUIRED PARTIES, PROHIBITED FROM SUPERVISING PHYSICIAN ASSISTANTS AND ADVANCED PRACTICE NURSES, SUBMITTING QUARTERLY DECLARATIONS OF COMPLIANCE WITH ALL CONDITIONS OF PROBATION, COMPLYING WITH BOARD'S PROBATION UNIT, PROHIBITED FROM ENGAGING IN THE PRACTICE OF MEDICINE IN DR. BENATTI ATWOOD'S OR PATIENT'S PLACE OF RESIDENCE, UNLESS THE PATIENT RESIDES IN A SKILLED NURSING FACILITY OR OTHER SIMILAR LICENSED FACILITY, AND PAYING COSTS ASSOCIATED WITH PROBATION MONITORING.",
        },
        {
            age_of_probation: '5 Years, 0 Months, and 0 Days',
            casenumber: '8002015018436',
            effective_date: '02-Nov-2017',
            end_date: '02-Nov-2022',
            prov: '1542',
            prov_firstname: 'Nyree',
            prov_lastname: 'Padilla',
            pstatus: '11',
            status: 'incomplete',
            summary:
                'FIVE YEARS PROBATION VARIOUS TERMS CONDITIONS PROBATION ATWOOD PROHIBITED SUPERVISING PHYSICIAN ASSISTANTS ADVANCED PRACTICE NURSES.',
        },
    ],
    Provider: {
        about: 'Dummy',
        badge: {
            badge: 'Bronze',
            badge_type: 'Bronze',
            icon: 'http://10.0.0.25/media/static/img/star_empty_J3iES2w.png',
            tier: '1',
        },
        icon: 'http://10.0.0.25/media/static/img/158927_6IGzGKC_YrQuS8o_HPZyBVY.jpg',
        npi: 1234567890,
        preferred_name: 'Padilla',
        prov_taxonomy_code: 'Allergy',
        provider: { user: user3 },
        provider_id: 1542,
        salutation: null,
        specialty_code: 'ALLERGY',
        tip: 'Dummy',
        votee: 0,
    },
    QueueConfig: {
        capacity: 15,
        close_time: '18:00:00',
        end_before_close: 1,
        est_wait_time: 2,
        inqueue: -1,
        open_time: '06:00:00',
        pause_time: 1,
        prov: '1542',
        prov_firstname: 'Nyree',
        prov_lastname: 'Padilla',
        status: 'A',
        time_before_noshow: 1,
        time_between_patients: 0,
    },
    Ratings: [
        { rating: 216, type: 'doctor' },
        { rating: 73, type: 'staff' },
        { rating: 66, type: 'office' },
        { rating: 60, type: 'bedisde' },
    ],
};
const provider3 = {
    Accusations: [],
    Actions: [],
    Arbitrations: [],
    Citations: [
        {
            amount: 350,
            cause: 'VIOLATION OF TERM OR CONDITION OF PROBATION.',
            datecitationissued: '06-Dec-2018',
            dateresolved: '2018-12-21 06:00:00+00:00',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            resolved: 'Y',
        },
    ],
    Convictions: [
        {
            classs: 'MISDEMEANOR',
            court: 'SUPERIOR COURT OF CALIFORNIA, COUNTY OF SAN DIEGO',
            effective_date: '30-Mar-2015',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            sentence: 'FIVE YEARS PROBATION WITH TERMS AND CONDITIONS.',
            summary:
                'PLED GUILTY TO TWO COUNTS OF VIOLATING PENAL CODE SECTION 273.5(A) (CORPORAL INJURY ON SPOUSE OR COHABITANT).',
        },
    ],
    License: [
        {
            licensenumber: '137214',
            licensetype: 'A',
            no_practice_permitted: '0',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            shortdescription: 'Current',
        },
    ],
    Malpractices: [],
    Number_negatives_v: [],
    Number_of_negatives: [
        { prov: '1542', prov_firstname: 'David', prov_lastname: 'Wade', sum: 3 },
    ],
    Probations: [
        {
            age_of_probation: '5 Years, 0 Months, and 0 Days',
            casenumber: '8002015018436',
            effective_date: '02-Nov-2017',
            end_date: '02-Nov-2022',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            pstatus: '11',
            status: 'incomplete',
            summary:
                "DR. BENATTI ATWOOD ADMITTED TO BEING CONVICTED OF A MISDEMEANOR COUNT OF CORPORAL INJURY ON A SPOUSE OR COHABITANT; USING DRUGS IN A MANNER AS TO BE DANGEROUS OR INJURIOUS TO HIMSELF, ANOTHER PERSON, OR TO THE PUBLIC; AND ENGAGING IN UNPROFESSIONAL CONDUCT.  EFFECTIVE 11/02/2017, REVOKED, STAYED, PLACED ON FIVE YEARS' PROBATION UNTIL ANTICIPATED END DATE OF 11/02/2022.  TERMS AND CONDITIONS INCLUDE, BUT ARE NOT LIMITED TO, ABSTAINING FROM THE USE OF CONTROLLED SUBSTANCES AND ALCOHOL, COMPLETING AN ETHICS COURSE AND AN ANGER MANAGEMENT COURSE, SUBMITTING TO A PSYCHIATRIC EVALUATION, ATTENDING PSYCHOTHERAPY, NOTIFICATION OF EMPLOYER, SUBMITTING TO BIOLOGICAL FLUID TESTING, ATTENDING SUBSTANCE ABUSE SUPPORT GROUP MEETINGS, OBTAINING A WORKSITE MONITOR, SUBMITTING PROOF OF NOTIFICATION OF DECISION AND ACCUSATION TO REQUIRED PARTIES, PROHIBITED FROM SUPERVISING PHYSICIAN ASSISTANTS AND ADVANCED PRACTICE NURSES, SUBMITTING QUARTERLY DECLARATIONS OF COMPLIANCE WITH ALL CONDITIONS OF PROBATION, COMPLYING WITH BOARD'S PROBATION UNIT, PROHIBITED FROM ENGAGING IN THE PRACTICE OF MEDICINE IN DR. BENATTI ATWOOD'S OR PATIENT'S PLACE OF RESIDENCE, UNLESS THE PATIENT RESIDES IN A SKILLED NURSING FACILITY OR OTHER SIMILAR LICENSED FACILITY, AND PAYING COSTS ASSOCIATED WITH PROBATION MONITORING.",
        },
        {
            age_of_probation: '5 Years, 0 Months, and 0 Days',
            casenumber: '8002015018436',
            effective_date: '02-Nov-2017',
            end_date: '02-Nov-2022',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            pstatus: '11',
            status: 'incomplete',
            summary:
                'FIVE YEARS PROBATION VARIOUS TERMS CONDITIONS PROBATION ATWOOD PROHIBITED SUPERVISING PHYSICIAN ASSISTANTS ADVANCED PRACTICE NURSES.',
        },
    ],
    Provider: {
        about: 'Dummy',
        badge: {
            badge: 'Bronze',
            badge_type: 'Bronze',
            icon: 'http://10.0.0.25/media/static/img/star_empty_J3iES2w.png',
            tier: '1',
        },
        icon: 'http://10.0.0.25/media/static/img/158927_6IGzGKC_YrQuS8o_HPZyBVY.jpg',
        npi: 1234567890,
        preferred_name: 'Wade',
        prov_taxonomy_code: 'Allergy',
        provider: { user: user2 },
        provider_id: 1542,
        salutation: null,
        specialty_code: 'ALLERGY',
        tip: 'Dummy',
        votee: 0,
    },
    QueueConfig: {
        capacity: 15,
        close_time: '18:00:00',
        end_before_close: 1,
        est_wait_time: 2,
        inqueue: -1,
        open_time: '06:00:00',
        pause_time: 1,
        prov: '1542',
        prov_firstname: 'David',
        prov_lastname: 'Wade',
        status: 'A',
        time_before_noshow: 1,
        time_between_patients: 0,
    },
    Ratings: [
        { rating: 216, type: 'doctor' },
        { rating: 73, type: 'staff' },
        { rating: 66, type: 'office' },
        { rating: 60, type: 'bedisde' },
    ],
};
const provider4 = {
    Accusations: [],
    Actions: [],
    Arbitrations: [],
    Citations: [
        {
            amount: 350,
            cause: 'VIOLATION OF TERM OR CONDITION OF PROBATION.',
            datecitationissued: '06-Dec-2018',
            dateresolved: '2018-12-21 06:00:00+00:00',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            resolved: 'Y',
        },
    ],
    Convictions: [
        {
            classs: 'MISDEMEANOR',
            court: 'SUPERIOR COURT OF CALIFORNIA, COUNTY OF SAN DIEGO',
            effective_date: '30-Mar-2015',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            sentence: 'FIVE YEARS PROBATION WITH TERMS AND CONDITIONS.',
            summary:
                'PLED GUILTY TO TWO COUNTS OF VIOLATING PENAL CODE SECTION 273.5(A) (CORPORAL INJURY ON SPOUSE OR COHABITANT).',
        },
    ],
    License: [
        {
            licensenumber: '137214',
            licensetype: 'A',
            no_practice_permitted: '0',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            shortdescription: 'Current',
        },
    ],
    Malpractices: [],
    Number_negatives_v: [],
    Number_of_negatives: [
        { prov: '1542', prov_firstname: 'David', prov_lastname: 'Wade', sum: 3 },
    ],
    Probations: [
        {
            age_of_probation: '5 Years, 0 Months, and 0 Days',
            casenumber: '8002015018436',
            effective_date: '02-Nov-2017',
            end_date: '02-Nov-2022',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            pstatus: '11',
            status: 'incomplete',
            summary:
                "DR. BENATTI ATWOOD ADMITTED TO BEING CONVICTED OF A MISDEMEANOR COUNT OF CORPORAL INJURY ON A SPOUSE OR COHABITANT; USING DRUGS IN A MANNER AS TO BE DANGEROUS OR INJURIOUS TO HIMSELF, ANOTHER PERSON, OR TO THE PUBLIC; AND ENGAGING IN UNPROFESSIONAL CONDUCT.  EFFECTIVE 11/02/2017, REVOKED, STAYED, PLACED ON FIVE YEARS' PROBATION UNTIL ANTICIPATED END DATE OF 11/02/2022.  TERMS AND CONDITIONS INCLUDE, BUT ARE NOT LIMITED TO, ABSTAINING FROM THE USE OF CONTROLLED SUBSTANCES AND ALCOHOL, COMPLETING AN ETHICS COURSE AND AN ANGER MANAGEMENT COURSE, SUBMITTING TO A PSYCHIATRIC EVALUATION, ATTENDING PSYCHOTHERAPY, NOTIFICATION OF EMPLOYER, SUBMITTING TO BIOLOGICAL FLUID TESTING, ATTENDING SUBSTANCE ABUSE SUPPORT GROUP MEETINGS, OBTAINING A WORKSITE MONITOR, SUBMITTING PROOF OF NOTIFICATION OF DECISION AND ACCUSATION TO REQUIRED PARTIES, PROHIBITED FROM SUPERVISING PHYSICIAN ASSISTANTS AND ADVANCED PRACTICE NURSES, SUBMITTING QUARTERLY DECLARATIONS OF COMPLIANCE WITH ALL CONDITIONS OF PROBATION, COMPLYING WITH BOARD'S PROBATION UNIT, PROHIBITED FROM ENGAGING IN THE PRACTICE OF MEDICINE IN DR. BENATTI ATWOOD'S OR PATIENT'S PLACE OF RESIDENCE, UNLESS THE PATIENT RESIDES IN A SKILLED NURSING FACILITY OR OTHER SIMILAR LICENSED FACILITY, AND PAYING COSTS ASSOCIATED WITH PROBATION MONITORING.",
        },
        {
            age_of_probation: '5 Years, 0 Months, and 0 Days',
            casenumber: '8002015018436',
            effective_date: '02-Nov-2017',
            end_date: '02-Nov-2022',
            prov: '1542',
            prov_firstname: 'David',
            prov_lastname: 'Wade',
            pstatus: '11',
            status: 'incomplete',
            summary:
                'FIVE YEARS PROBATION VARIOUS TERMS CONDITIONS PROBATION ATWOOD PROHIBITED SUPERVISING PHYSICIAN ASSISTANTS ADVANCED PRACTICE NURSES.',
        },
    ],
    Provider: {
        about: 'Dummy',
        badge: {
            badge: 'Bronze',
            badge_type: 'Bronze',
            icon: 'http://10.0.0.25/media/static/img/star_empty_J3iES2w.png',
            tier: '1',
        },
        icon: 'http://10.0.0.25/media/static/img/158927_6IGzGKC_YrQuS8o_HPZyBVY.jpg',
        npi: 1234567890,
        preferred_name: 'Wade',
        prov_taxonomy_code: 'Allergy',
        provider: { user: user4 },
        provider_id: 1542,
        salutation: null,
        specialty_code: 'ALLERGY',
        tip: 'Dummy',
        votee: 0,
    },
    QueueConfig: {
        capacity: 15,
        close_time: '18:00:00',
        end_before_close: 1,
        est_wait_time: 2,
        inqueue: -1,
        open_time: '06:00:00',
        pause_time: 1,
        prov: '1542',
        prov_firstname: 'David',
        prov_lastname: 'Wade',
        status: 'A',
        time_before_noshow: 1,
        time_between_patients: 0,
    },
    Ratings: [
        { rating: 216, type: 'doctor' },
        { rating: 73, type: 'staff' },
        { rating: 66, type: 'office' },
        { rating: 60, type: 'bedisde' },
    ],
};
