

export const queue1: Queue = {
    queue: { from: 'provider', member: undefined, provider: 1542 },
    queuedata: {
        queueA: undefined,
        queueB: undefined,
        queueI: [
            {
                est_wait_time: 15,
                join_date: '2024-04-25T10:00:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1760 },
                p_status: 'pending',
                position: 1,
                prov: 1542,
            },
            {
                est_wait_time: 30,
                join_date: '2024-04-25T09:45:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1761 },
                p_status: 'pending',
                position: 2,
                prov: 1542,
            },
        ],
        queueS: [
            {
                est_wait_time: 20,
                join_date: '2024-04-25T09:30:00Z',
                leave_date: null,
                m_status: 'seen',
                member: { id: 1762 },
                p_status: 'completed',
                position: 1,
                prov: 1542,
            },
        ],
        queueW: undefined,
        queueitem: undefined,
        status: undefined,
    },
};
export const queue2: Queue = {
    queue: { from: 'provider', member: undefined, provider: 1542 },
    queuedata: {
        queueA: undefined,
        queueB: undefined,
        queueI: [
            {
                est_wait_time: 15,
                join_date: '2024-04-25T10:00:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1760 },
                p_status: 'pending',
                position: 1,
                prov: 1542,
            },
            {
                est_wait_time: 30,
                join_date: '2024-04-25T09:45:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1761 },
                p_status: 'pending',
                position: 2,
                prov: 1542,
            },
        ],
        queueS: [
            {
                est_wait_time: 20,
                join_date: '2024-04-25T09:30:00Z',
                leave_date: null,
                m_status: 'seen',
                member: { id: 1762 },
                p_status: 'completed',
                position: 1,
                prov: 1542,
            },
        ],
        queueW: undefined,
        queueitem: undefined,
        status: undefined,
    },
};
export const queue3: Queue = {
    queue: { from: 'provider', member: undefined, provider: 1542 },
    queuedata: {
        queueA: undefined,
        queueB: undefined,
        queueI: [
            {
                est_wait_time: 15,
                join_date: '2024-04-25T10:00:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1760 },
                p_status: 'pending',
                position: 1,
                prov: 1542,
            },
            {
                est_wait_time: 30,
                join_date: '2024-04-25T09:45:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1761 },
                p_status: 'pending',
                position: 2,
                prov: 1542,
            },
        ],
        queueS: [
            {
                est_wait_time: 20,
                join_date: '2024-04-25T09:30:00Z',
                leave_date: null,
                m_status: 'seen',
                member: { id: 1762 },
                p_status: 'completed',
                position: 1,
                prov: 1542,
            },
        ],
        queueW: undefined,
        queueitem: undefined,
        status: undefined,
    },
};
export const queue4: Queue = {
    queue: { from: 'provider', member: undefined, provider: 1542 },
    queuedata: {
        queueA: undefined,
        queueB: undefined,
        queueI: [
            {
                est_wait_time: 15,
                join_date: '2024-04-25T10:00:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1760 },
                p_status: 'pending',
                position: 1,
                prov: 1542,
            },
            {
                est_wait_time: 30,
                join_date: '2024-04-25T09:45:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1761 },
                p_status: 'pending',
                position: 2,
                prov: 1542,
            },
        ],
        queueS: [
            {
                est_wait_time: 20,
                join_date: '2024-04-25T09:30:00Z',
                leave_date: null,
                m_status: 'seen',
                member: { id: 1762 },
                p_status: 'completed',
                position: 1,
                prov: 1542,
            },
        ],
        queueW: undefined,
        queueitem: undefined,
        status: undefined,
    },
};
export const queue5: Queue = {
    queue: { from: 'provider', member: undefined, provider: 1542 },
    queuedata: {
        queueA: undefined,
        queueB: undefined,
        queueI: [
            {
                est_wait_time: 15,
                join_date: '2024-04-25T10:00:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1760 },
                p_status: 'pending',
                position: 1,
                prov: 1542,
            },
            {
                est_wait_time: 30,
                join_date: '2024-04-25T09:45:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1761 },
                p_status: 'pending',
                position: 2,
                prov: 1542,
            },
        ],
        queueS: [
            {
                est_wait_time: 20,
                join_date: '2024-04-25T09:30:00Z',
                leave_date: null,
                m_status: 'seen',
                member: { id: 1762 },
                p_status: 'completed',
                position: 1,
                prov: 1542,
            },
        ],
        queueW: undefined,
        queueitem: undefined,
        status: undefined,
    },
};
export const queue6: Queue = {
    queue: { from: 'provider', member: undefined, provider: 1542 },
    queuedata: {
        queueA: undefined,
        queueB: undefined,
        queueI: [
            {
                est_wait_time: 15,
                join_date: '2024-04-25T10:00:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1760 },
                p_status: 'pending',
                position: 1,
                prov: 1542,
            },
            {
                est_wait_time: 30,
                join_date: '2024-04-25T09:45:00Z',
                leave_date: null,
                m_status: 'waiting',
                member: { id: 1761 },
                p_status: 'pending',
                position: 2,
                prov: 1542,
            },
        ],
        queueS: [
            {
                est_wait_time: 20,
                join_date: '2024-04-25T09:30:00Z',
                leave_date: null,
                m_status: 'seen',
                member: { id: 1762 },
                p_status: 'completed',
                position: 1,
                prov: 1542,
            },
        ],
        queueW: undefined,
        queueitem: undefined,
        status: undefined,
    },
};
