export const user1 = {
    city: 'Roseville',
    email: 'Benatti.atwood.david.wade@provider.com',
    first_name: 'David',
    icon: null,
    last_name: 'Wade',
    middle_name: 'Benatti atwood',
    phone_number: '',
    state: 'CA',
    street_address: '751 central park dr # 912',
    street_address2: '912',
    username: 'Benatti.atwood.david.wade@provider.com',
    zipcode: '95678',
};
export const user2 = {
    city: 'Roseville',
    email: 'Admire.anthony.allan@provider.com',
    first_name: 'Anthony',
    icon: null,
    last_name: 'Allan',
    middle_name: 'Admire',
    phone_number: '',
    state: 'CA',
    street_address: '7231 e princess blvd ste 211',
    street_address2: '',
    username: 'Admire.anthony.allan@provider.com',
    zipcode: '95678',
};
export const user3 = {
    city: 'Boston',
    email: 'Padilla.nyree@provider.com',
    first_name: 'Nyree',
    icon: null,
    last_name: 'Padilla',
    middle_name: '',
    phone_number: '',
    state: 'MA',
    street_address: '75 state st fl 26',
    street_address2: '',
    username: 'Padilla.nyree@provider.com',
    zipcode: '02109',
};
export const user4 = {
    city: 'Anaheim',
    email: 'Ly.jane.truc@provider.com',
    first_name: 'Jane',
    icon: null,
    last_name: 'Truc',
    middle_name: 'Ly',
    phone_number: '',
    state: 'CA',
    street_address: '921 s nordica st',
    street_address2: '',
    username: 'Ly.jane.truc@provider.com',
    zipcode: '92806',
};


export const user6 = {
    city: 'Roseville',
    email: 'melaniealvarez@example.com',
    first_name: 'Nancy',
    icon: null,
    last_name: 'Matthew',
    middle_name: 'Clark',
    phone_number: '',
    state: 'CA',
    street_address: '15493 Maurice Spur Apt. 467',
    street_address2: '',
    username: 'nancybell',
    zipcode: '95678',
};
export const user7 = {
    city: 'Roseville',
    email: 'zpatterson@example.com',
    first_name: 'Michael',
    icon: null,
    last_name: 'Patterson',
    middle_name: 'Richardson',
    phone_number: '',
    state: 'CA',
    street_address: '3286 Becker Courts',
    street_address2: '',
    username: 'stephenparsons',
    zipcode: '95678',
};
export const user8 = {
    city: 'Roseville',
    email: 'bradley34@example.org',
    first_name: 'Bradley',
    icon: null,
    last_name: 'Nolen',
    middle_name: 'Davis',
    phone_number: '',
    state: 'CA',
    street_address: '7928 Glen tree dr',
    street_address2: '',
    username: 'bradley34@example.org',
    zipcode: '95678',
};
export const user9 = {
    city: 'Roseville',
    email: 'iwalker@example.com',
    first_name: 'Angel',
    icon: null,
    last_name: 'Julie',
    middle_name: 'Yoder',
    phone_number: '',
    state: 'CA',
    street_address: '8017 Moore Vista Suite 129',
    street_address2: '',
    username: 'natalieallen',
    zipcode: '95678',
};
